### ISSUE TITLE
Pseduo code in README

### ISSUE THREAD

**Issue by hanneslehmann** [go-cmd/cmd#27]
There are some issues in your README - example, which prevents users to copy and paste it to test.

Mainly: 
```go
status := c.Status() -> c never declared. 
```

```go
finalStatus -> never used
``` 

and main function missing. Wouldn't it be better to show off a running code snippet instead of a pseudo code?

**Comment by croqaz** [comment]
Thank you @hanneslehmann for raising this issue.

You're right it was a problem with the pseudo code in the Readme.

I have fixed the "c" variable and the "main" function.

For the "finalStatus" I'm not updating the code, because it's added in there just to point out that you can use it in that context, so it's OK.
