### ISSUE TITLE
Appropriate way to handle STDIN?

### ISSUE THREAD

**Issue by sb3tcs** [go-cmd/cmd#29]
Howdy.

We are in process of evaluating this package to help streamline running external processes however it is already plausible in our use cases that writing to STDIN would be of value. What route is recommended for writing to STDIN with this package? Seems we will have to modify it to support this but perhaps there are lessons learned that could be discussed here.

If we end up going with this go-cmd, would a PR for STDIN support be in line with the vision of this package, @daniel-nichter ?

Thank you for your time.

**Comment by daniel-nichter** [comment]
Hi. Unfortunately, that's not possible with this pkg because you'd need to set `Stdin io.Reader` in the underlying `os/exec.Cmd` object but this pkg doesn't expose that object.

Given this and other additions/requests, I think the best refactoring or addition (e.g. v1.1 of this pkg) would be to allow the user to pass in a low-level`os/exec.Cmd` so they can modify whatever low-level settings they want while still getting the high-level benefits of this pkg.

**Comment by daniel-nichter** [comment]
@juanenriqueescobar did this in https://github.com/go-cmd/cmd/pull/50. It has been merged to master and released as v1.2.1.

**Comment by ramikalai** [comment]
@daniel-nichter Does the implementation in #50 support writing to stdin at any time while the command is running?

Also, would really appreciate an example of usage for a cmd that is started with StartWithStdin()
