### ISSUE TITLE
When launching the same binary, one instance closes the other

### ISSUE THREAD

**Issue by itapai** [go-cmd/cmd#41]
Hi,

so this is the snipper. 

```
package main

import (
	"log"
	"time"

	"github.com/go-cmd/cmd"
)

func main() {
	p1 := cmd.NewCmd("chromium")
	p1done := p1.Start()
	go func() {
		select {
		case pp1 := <-p1done:
			log.Println(pp1)
		}
	}()

	p2 := cmd.NewCmd("chromium")
	p2done := p2.Start()
	go func() {
		select {
		case pp2 := <-p2done:
			log.Println(pp2)
		}
	}()

	time.Sleep(time.Second * 20)
}

```

When running the code, there is p1 exit or p2 exit in the output, but the windows are still running. 
I believe it has got something to do with how chromium handles multiple windows. But I also think that a message should be sent over the channel, if the process is still running.
Same thing happens for other GUI apps as well. 

Am I missing something?

**Comment by daniel-nichter** [comment]
Nothing with respect to this package looks wrong. p1 and p2 should be completely separate and independent processes, but there's no telling what chromium is doing. It's possible it writes a shared PID file, so when p1 starts and write the PID file, then p2 starts and sees the PID file already exists, it kills p1.

Since this isn't a bug with this package, I'll close this issue.
