### ISSUE TITLE
How to test executed commands

### ISSUE THREAD

**Issue by lneves12** [go-cmd/cmd#45]
Any tip on how to mock a command execution for testing?

I tried the trick from here: https://npf.io/2015/06/testing-exec-command/ but it's not working properly
```golang 
// cmd.go tweak

var ComandExecuter = exec.Command

func (c *Cmd) run() {
	defer func() {
		c.statusChan <- c.Status() // unblocks Start if caller is waiting
		close(c.doneChan)
	}()

	// //////////////////////////////////////////////////////////////////////
	// Setup command
	// //////////////////////////////////////////////////////////////////////
	cmd := ComandExecuter(c.Name, c.Args...)

```

**Comment by lneves12** [comment]
https://github.com/go-cmd/cmd/pull/46

**Comment by daniel-nichter** [comment]
Hi. Going to reject that PR because this pkg is not, imho, the correct level at which to handle this. (Also, global variables are bad.) You want something like https://github.com/go-cmd/run. So rather than mocking the low-level cmd itself, you introduce a higher layer of abstraction into your code: something that runs commands. Then you have real cmd runners and mock/test command runners. That's essentially what https://npf.io/2015/06/testing-exec-command/ is doing, but it's using a global var as a convenience/shortcut.
