### ISSUE TITLE
python command in streaming mode not streaming the stdout

### ISSUE THREAD

**Issue by snirbenyosef** [go-cmd/cmd#90]
Hey, thank you so much for the hard work building this package!

I have created a function that takes command and run it, and prints the stdout/stderr live.
I have 1 issue when I run the below code, the prints start only after the command is finished, but when I add -u to the command its starts printing and I don't want to use the -u flag on python. this is not happening if I use the exec go build-in, so I will appreciate any insight here.

```
	cmdOptions := cmd.Options{
		Buffered:  false,
		Streaming: true,
	}
	envCmd := cmd.NewCmdOptions(cmdOptions, "python3", "train.py")
	
	for envCmd.Stdout != nil || envCmd.Stderr != nil {
			select {
			case line, open := <-envCmd.Stdout:
				if !open {
					envCmd.Stdout = nil
					continue
				}
				fmt.Println(line)
			case line, open := <-envCmd.Stderr:
				if !open {
					envCmd.Stderr = nil
					continue
				}
				fmt.Fprintln(os.Stderr, line)
			}
		}
```

**Comment by daniel-nichter** [comment]
Hi. Sorry for slow reply. I'm not a Python expert but from what I've read Python buffers its output by default, so `cmd` isn't receiving anything from Python until the end. That's why `-u` works: it turns off buffering, making Python print output immediately, which makes `cmd`  streaming working.

In the Python docs, I read:

>Changed in version 3.7: The text layer of the stdout and stderr streams now is unbuffered.

So maybe this has changed in that version of Python? Worth trying it.
